;; Keywords
(("return"   @keyword) (#set! conceal "󰄽"))
(("local"    @keyword) (#set! conceal "~"))
(("if"       @keyword) (#set! conceal "?"))
(("then"     @keyword) (#set! conceal ""))
(("else"     @keyword) (#set! conceal "!"))
(("elseif"   @keyword) (#set! conceal "¿"))
(("function" @keyword) (#set! conceal ""))
(("for"      @keyword) (#set! conceal ""))
(("end"      @keyword) (#set! conceal ""))
(("do"       @keyword) (#set! conceal "󰜰"))